inventory_group_all_user_profile:
  vscode:
    extenssions:
      - alefragnani.project-manager
      - CoenraadS.bracket-pair-colorizer-2
      - haaaad.ansible
      - wholroyd.jinja
      - donjayamanne.githistory
