all:
  children:
    routeros:
      hosts:
        mr-rou-001.rachuna.net:
    workstasion:
      hosts:
        localhost:
    jenkins:
      children:
        jenkins_master:
          hosts:
            jenkins-master.rachuna.net:
        jenkins_slave_linux:
          hosts:
            jenkins-slave.rachuna.net: