all:
  children:
    routeros:
      hosts:
        router.rachuna.net:
    workstastions:
      hosts:
        localhost:
    jenkins:
      children:
        jenkins_master:
          hosts:
            jenkins-master-centos.rachuna.net:
            jenkins-master-ubuntu.rachuna.net:
        jenkins_slave_linux:
          hosts:
            jenkins-slave-centos.rachuna.net:
            jenkins-slave-ubuntu.rachuna.net:
    docker_server:
      hosts:
        docker-002.rachuna.net:
    workstasion:
      hosts:
        mr-nbo-002.rachuna.net:
    workstastions:
      hosts:
        # mr-nbo-002.rachuna.net:
        mr-usr-vm-100.rachuna.net: