all:
  children:
    routeros:
      hosts:
        router.rachuna.net:
    workstastions:
      hosts:
        localhost:
    jenkins:
      children:
        jenkins_master:
          hosts:
            jenkins-master.rachuna.net:
        jenkins_slave_linux:
          hosts:
            jenkins-slave.rachuna.net:
    docker_server:
      hosts:
        docker-002.rachuna.net: