invenory_group_jenkins_master_app_configuration:
  master_number_of_executors: 10
  httpPort: 443
  slaveAgentPort: 50000
  location:
    adminAddress: jenkins@localhost
    url: "http://jenkins-master.rachuna.net:443"           # ha-proxy address
  sharedlibraries:
    - name: "Sharedlibraries"
      branch: "feature/class"
      gitUrl: "git@github.com:wolfsea89/Jenkins-Sharedlibraries.git"
      credentialsId: "github"