inventory_group_jenkins_master_credentials:
  jenkins_master:
    description:             "Jenkins Master private ssh key"
    type:                    "basicSSHUserPrivateKey"
    passphrase:              ""
    username:                "jenkins"
    privateKey:              "{{ inventory_group_jenkins_ssh_key.private_ssh_key }}"

  github:
    description:             "GitHub private ssh key"
    type:                    "basicSSHUserPrivateKey"
    passphrase:              ""
    username:                "<< github_jenkins >>"
    privateKey:              "{{ inventory_group_jenkins_ssh_key.private_ssh_key }}"

  github_token:
    description:             "GitHub Jenkins Token"
    type:                    "usernamePassword"
    username:                "<< github_user >>"
    password:                "<< token >>"

  docker_hub:
    description:             "Docker hub access token"
    type:                    "usernamePassword"
    username:                "<< docker_user >>"
    password:                "<< token >>"

  baseImage_services_AminPassword:
    description:             "Password for the administrator account added to dockerfile"
    type:                    "usernamePassword"
    username:                "<< admin >>"
    password:                "<< password"
