inventory_host_routeros_lists_interfaces:
  list_wan:
    name: LIST-WAN
    interfaces:
      - name: "{{ inventory_host_routeros_ethernet_interfaces.ether1.name }}"
        comment: "WAN"
  list_lan_users:
    name: LIST-LAN-USERS
    interfaces:
      - name: "{{ inventory_host_routeros_wireless_interfaces.wlan1.name }}"
      - name: "{{ inventory_host_routeros_wireless_interfaces.wlan2.name }}"
        comment: "LAN-USERS"
  list_lan_admins:
    name: LIST-LAN-ADMINS
    interfaces:
      - name: "{{ inventory_host_routeros_ethernet_interfaces.ether5.name }}"
        comment: "LAN-ADMINS"
  list_lan_proxmox:
    name: LIST-LAN-PROXMOX
    interfaces:
      - name: "{{ inventory_host_routeros_ethernet_interfaces.ether2.name }}"
      - name: "{{ inventory_host_routeros_ethernet_interfaces.ether3.name }}"
      - name: "{{ inventory_host_routeros_ethernet_interfaces.ether4.name }}"
        comment: "LAN-PROXMOX"
