inventory_group_routeros_dhcp_servers:
  admins_network_dhcp:
    name: "admins-network-dhcp"
    interface: "{{ inventory_host_routeros_ethernet_interfaces.ether5.name }}"
    address-pool: "{{ inventory_group_routeros_pools.admins_network_pool.name }}"

  proxmox_network_dhcp:
    name: "proxmox-network-dhcp"
    interface: "{{ inventory_host_routeros_bridge_interfaces.lan_prod.name }}"
    address-pool: "{{ inventory_group_routeros_pools.proxmox_network_pool.name }}"

  users_network_dhcp:
    name: "users-network-dhcp"
    interface: "{{ inventory_host_routeros_bridge_interfaces.lan_users.name }}"
    address-pool: "{{ inventory_group_routeros_pools.users_network_pool.name }}"
    insert-queue-before: bottom

  prod_network_dhcp:
    name: "prod-network-dhcp"
    interface: "VLAN-PROD"
    address-pool: "{{ inventory_group_routeros_pools.prod_network_pool.name }}"
    insert-queue-before: bottom
