iventory_group_routeros_dns_static_records:
  - name: "mr-rou-001.rachuna.net"
    address: "10.0.0.1"
    comment: "Router Mikrotik"
    disabled: "no"
    regexp: ""
    ttl: 1d
    type: 'A'

  - name: "router.rachuna.net"
    address: "10.0.0.1"
    comment: ""
    disabled: "no"
    regexp: ""
    ttl: 1d
    type: 'A'